spring:
  application:
    name: task-tracker

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework: info

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: 3600